### ISSUE TITLE
[feature] Use gin-gonic/gin for server mux

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#22]
**Is your feature request related to a problem? Please describe.**
The server currently uses cmux and protocol filtering. The protocol filtering is not reliable and can sometimes cause deadlock issues for client requests. 

**Describe the solution you'd like**
Switch to using github.com/gin-gonic/gin for http mux and use two separate ports. That will require more work for mapping API routes in the future, but it's not an immediate concern and can be resolved later. 

**Describe alternatives you've considered**
Tried using cmux and the same port, which sometimes works but is not reliable. 

**Additional context**
gin-gonic/gin has better performance for request routing, so it will be another improvement in the server.

**Comment by dhirajsb** [comment]
@lampajr try doing protocol filtering using gin, it might be more capable and we might be able to get away with using a single port for both gRPC and GraphQL.

**Comment by lampajr** [comment]
Hey @dhirajsb after some investigation it seems that we if want to keep both servers running on the same port `cmux` seems already a good choice, I did not find a real value on switching to `gin`, do you?

On the other hand IMO it would be better to have different servers running on different ports, in this way all servers are "isolated" and they can be easily switched on/off, thus I was thinking of creating different commands in order to startup different servers like `serve` to stat gRPC, `graphql` to start the GraphQL server and maybe another `gateway` to start gRPC gateway. Wdyt?

**Comment by rareddy** [comment]
IMO this is not "required" but nice to have, so we should defer this experimentation for later.

**Comment by tarilabs** [comment]
closing as "not planned now" and labelled as requested, per Scrum decision 2023-10-30
