### ISSUE TITLE
[feature] Externalize the DDL for the Database schema

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#33]
**Is your feature request related to a problem? Please describe.**

Right now the code to generate the database schema is embedded inside the `gorm` classes, however, it is preferable to externalize this and use a solution like `liquidbase` for version management. There may be different equivalent libraries for Go

**Describe the solution you'd like**

@dhirajsb mentioned a tool `Atlas`, for the needs of this. We need to do a spike on this feature.

**Comment by dhirajsb** [comment]
Since we have a plan to accomplish this using Gorm migrations support, can we close this issue?

**Comment by rareddy** [comment]
yes, as per discussion on #wg-model-registry the form `migrate` should provide the similar functionality to liquidbase/flyway but the migrations written using `gorm`. The advantage is the code generated will be DB specific and no need to maintain the individual dialects.

@dhirajsb do you want to start at version 10 of the schema as ml-metadata shows, then keep track from there? I wondering how do we make sure all the currently designed indexes and any other quirky DB features are correctly captured in the form metadata when `gorm` DB objects are designed.

**Comment by dhirajsb** [comment]
All the gorm DDL config is captured in `gorm` tags in the DB structs source code. Once we switch to using migrations, we can use the `date` signature like rhosak `migrations.go` and use that to identify schema versions. That way we could have multiple schema migrations captured in a single release cycle. 
It also makes it easier to identify when a particular design change was made, instead of a magical schema version number that has to be externally tied to some release cycle, etc. Does that make sense?

**Comment by rareddy** [comment]
I get that, I am asking how to make sure what gorm has interms of metadata has a complete view of what was showing original projects.

**Comment by rareddy** [comment]
Since will be C++ as is this is no longer required now. Closing as won't do.
