### ISSUE TITLE
Implement the REST API Server for Model Registry

### ISSUE THREAD

**Issue by rareddy** [opendatahub-io/model-registry-bf4-kf#59]
**Is your feature request related to a problem? Please describe.**
In order for the UI and CLI tools to interact with the Model Registry a REST API server needs to be developed

**Describe the solution you'd like**
Using the OpenAPI definition defined in #44, write a Go lang REST API Server and implement the API. The go API created in #58 should be used to talk to C++ MLMD sever over the gRPC.  

Acceptance criteria:
- Wiring Core layer in Go to the "stubs" generated under `internal/server/openapi/api_model_registry_service_service.go`
- Demonstrate with test going through the REST interface (eg: Robot Framework, if possible)

**Comment by lampajr** [comment]
Worth to record that we already have a MLMD Go gRPC client in our repository, this is automatically generated by `protoc`. See `metadataStoreServiceClient` at https://github.com/opendatahub-io/model-registry/blob/main/internal/ml_metadata/proto/metadata_store_service_grpc.pb.go#L420.

Otherwise if for some reasons we do not want to include the MLMD protos in our repository, as well as we do not want to autogenerate the client, I found a MLMD Go client package (did not try yet) built by kubeflow community [1, 2]. Their approach seems exactly the one we used so far but the version of the package is not stable as it is `v0.0.0-20231005061415-2fbabd9eb8b2`. 

[1] https://pkg.go.dev/github.com/kubeflow/pipelines/third_party/ml-metadata@v0.0.0-20231005061415-2fbabd9eb8b2
[2] https://github.com/kubeflow/pipelines/tree/2fbabd9eb8b2dac8b4190468d71e30cd7cf96237/third_party/ml-metadata/go/ml_metadata
