### ISSUE TITLE
Design a logical model to capture model-serving environments

### ISSUE THREAD

**Issue by dhirajsb** [opendatahub-io/model-registry-bf4-kf#70]
**Is your feature request related to a problem? Please describe.**
Model registry like other registries such as mlflow needs to provide its users information about environments where models can be and are deployed. For example, mlflow uses a simple model where model versions can be deployed in `stage` and `production` environments.  

**Describe the solution you'd like**
A logical schema is needed to describe how users will see model-serving based environments and ML models deployed in these environments. The schema should be based on terminology commonly used by model-serving users and how they visualize various parts of the model-serving environment. 

Model registry has the following concepts:
* Context - a collection of artifacts, and executions (actions). Contexts can be nested to model collections of collections. 
* Artifacts - physical artifacts used as either input/output for actions. They represent datasets, and ML models. 
* Executions - actions performed in the odh environment. E.g. a `Deploy` execution would represent the action of deploying an ML model in a model-serving environment. 

The model-registry team will help map the logical schema mentioned above to these model-registry concepts. 

We also need a clear idea about when these metadata entities are created and updated, and who's responsible for managing them. The model registry acts as a metadata repository for producers and consumers of metadata. And producers and consumers decide when the data is logged/created and what actions to take based on presence/absence/contents of that metadata. 

**Describe alternatives you've considered**
Model registry team could come up a simple logical model in the short term. But it would be better to have model-serving team input to create a logical model that would work for the long term. 

**Additional context**
The simple logical model that was initially proposed came from what mlflow does. But user feedback is that the simple model is too restrictive and doesn't suite user needs to be able to create multiple deployment environments like `dev, test, integration, stage, and production`.

**Comment by dhirajsb** [comment]
@Jooho thanks for helping us with this. Please feel free to invite other model-serving members who can help or might have an opinion/input on this.

**Comment by dhirajsb** [comment]
Based on the discussion with model-serving team on Friday, we could go with a simple metadata model for now:
* `ServingEnvironment` - `Context` to represent a model serving environment which supports various serving runtimes and can deploy `InferenceServices`
* `InferenceService` - `Context` associated with a `RegisteredModel` to be deployed in a `ServingEnvironment`. 

The model-controller will only publish information about a _local_ `ServingEnvironment` in the model registry for now. 
The metadata names were suggested based on model-serving design and implementation details. 

Originally I thought about using higher level names such as `DeploymentEnvironment` and `ModelDeployment`. But if ML users (both data scientists and mlops engineers) are more familiar with the _serving_ and _inference_ terminology, then it's better to stick with names from the ml domain. 

wdyt?

**Comment by rareddy** [comment]
That makes sense to me. Let's see we can ping @Jooho @israel-hdez @VedantMahabaleshwarkar is good with nomenclature?

> Context associated with a RegisteredModel to be deployed in a ServingEnvironment.

should this be associated with `ModelVesion`? also `ModelVersion` -----deployed to---->*`ServingEnvironment`

**Comment by israel-hdez** [comment]
> But if ML users (both data scientists and mlops engineers) are more familiar with the _serving_ and _inference_ terminology

Probably, there is no common terminology.

I think MLOps will be familiar with both `ServingRuntime` and `InferenceService` CRDs.

Then, because the way ODH is designed, Data Scientists will be more familiar with "Model server" and "Model" terminology. AFAIK, DataScientists tend to be mostly familiar only with the process of "deploying a model" and the model servers tend to be confusing entities for them.

Maybe we shouldn't be trying to find a common terminology for the different roles.

That's ^ just my opinion and my 2cents about terminology.

> The model-controller will only publish information about a local ServingEnvironment in the model registry for now.

What is the model-controller on this context?

This may need a clear definition about what is a _model serving environment_. Is it really just something that supports various serving runtimes?

And what "local" would mean here? Is it a namespace, a cluster, a mix (i.e. no strong boundaries), or something else? If it is a namespace, it would mean you can have only one local environment (unless you are allowed to do groupings). If it is a cluster, you can have many.

I'm doing all these questions because I'm having difficulty to understand the _serving environment_. It has been mentioned that it could be like `dev` or `staging` and, depending on what "local" means, you may be able to have only one env, or many.

If I understand correctly, model serving should report to the registry the available environments. Perhaps my difficulty to understand this is, in part, because I'm not sure if current state of model-serving components are enough to correctly report the available envs, or if there would be technical gaps to cover.

On the other hand, a InferenceService/ModelDeployment, is quite clear to me.

> Originally I thought about using higher level names such as DeploymentEnvironment and ModelDeployment.

Personally, I like more the new `ServingEnvironment` name. Although, I liked more the previous `ModelDeployment` name. 

> should this be associated with ModelVesion? also ModelVersion -----deployed to---->*ServingEnvironment

If the registry will be aware of versions of a model, I do agree with this assuming a specific version of a model is what would be deployed (not just a RegisteredModel).

**Comment by rareddy** [comment]
@israel-hdez 
> This may need a clear definition about what is a model serving environment. Is it really just something that supports various serving runtimes?

ServingEnvironment != ServingRuntime

>And what "local" would mean here? Is it a namespace, 

Yes, it "local" would mean namespace scoped. we envisioned a central repository originally that works across many installations. This is "ServingEnvironment"

>because I'm not sure if current state of model-serving components are enough to correctly report the available envs, or if there would be technical gaps to cover.

This case is really coming upfront with Edge scenarios, so I am saying we can leave as single environment now, with edge we can see how this evolves

**Comment by dhirajsb** [comment]
There is a sequence diagram in #104 that describes how the various metadata entities will be created and used to serve a `RegisteredModel` in a `ServingEnvironment`.

**Comment by dhirajsb** [comment]
An initial version of the serving model has been added.
